/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PROVENANCE_H
#define PROVENANCE_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace provenance {

class Provenance : public RapidNetApplicationBase
{
public:
  static const string IMAGE;
  static const string PITERATE;
  static const string PLIST;
  static const string PTMP;
  static const string PREDICTION;

  static TypeId GetTypeId (void);

  Provenance ();

  virtual ~Provenance ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0Ins (Ptr<Tuple> image);

  virtual void R2Eca0Ins (Ptr<Tuple> image);

  virtual void R3_eca (Ptr<Tuple> pList);

  virtual void R4_eca (Ptr<Tuple> pIterate);

  virtual void R5_eca (Ptr<Tuple> pIterate);

};

} // namespace provenance
} // namespace rapidnet
} // namespace ns3

#endif // PROVENANCE_H
