## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('provenance', ['internet-stack'])
    module.source = [
        'provenance.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'provenance'
    headers.source = [
        'provenance.h',
        'provenance-helper.h',
        ]
