/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef MLPROVENANCE_H
#define MLPROVENANCE_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace mlprovenance {

class Mlprovenance : public RapidNetApplicationBase
{
public:
  static const string ASSOCIATIONRULE;
  static const string CITERATE;
  static const string CLIST;
  static const string CLF;
  static const string IDENTIFIEDPATTERN;
  static const string IMAGE;
  static const string PCLF;
  static const string PITERATE;
  static const string PLIST;
  static const string PREDICTION;
  static const string RESULT;

  static TypeId GetTypeId (void);

  Mlprovenance ();

  virtual ~Mlprovenance ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0Ins (Ptr<Tuple> clf);

  virtual void R1_eca (Ptr<Tuple> pClf);

  virtual void R2_eca (Ptr<Tuple> pList);

  virtual void R3_eca (Ptr<Tuple> pIterate);

  virtual void R4_eca (Ptr<Tuple> pIterate);

  virtual void R5Eca0Ins (Ptr<Tuple> associationrule);

  virtual void R5Eca1Ins (Ptr<Tuple> prediction);

  virtual void R6_eca (Ptr<Tuple> identifiedPattern);

  virtual void R7_eca (Ptr<Tuple> cList);

  virtual void R8_eca (Ptr<Tuple> cIterate);

  virtual void R9_eca (Ptr<Tuple> cIterate);

};

} // namespace mlprovenance
} // namespace rapidnet
} // namespace ns3

#endif // MLPROVENANCE_H
