/* A RapidNet application. Generated by RapidNet compiler. */

#include "mlprovenance.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::mlprovenance;

const string Mlprovenance::ASSOCIATIONRULE = "associationrule";
const string Mlprovenance::CITERATE = "cIterate";
const string Mlprovenance::CLIST = "cList";
const string Mlprovenance::CLF = "clf";
const string Mlprovenance::IDENTIFIEDPATTERN = "identifiedPattern";
const string Mlprovenance::IMAGE = "image";
const string Mlprovenance::PCLF = "pClf";
const string Mlprovenance::PITERATE = "pIterate";
const string Mlprovenance::PLIST = "pList";
const string Mlprovenance::PREDICTION = "prediction";
const string Mlprovenance::RESULT = "result";

NS_LOG_COMPONENT_DEFINE ("Mlprovenance");
NS_OBJECT_ENSURE_REGISTERED (Mlprovenance);

TypeId
Mlprovenance::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::mlprovenance::Mlprovenance")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<Mlprovenance> ()
    ;
  return tid;
}

Mlprovenance::Mlprovenance()
{
  NS_LOG_FUNCTION_NOARGS ();
}

Mlprovenance::~Mlprovenance()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
Mlprovenance::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
Mlprovenance::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("Mlprovenance Application Started");
}

void
Mlprovenance::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("Mlprovenance Application Stopped");
}

void
Mlprovenance::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (ASSOCIATIONRULE, attrdeflist (
    attrdef ("associationrule_attr1", IPV4),
    attrdef ("associationrule_attr2", IPV4),
    attrdef ("associationrule_attr3", IPV4)));

  AddRelationWithKeys (CLF, attrdeflist (
    attrdef ("clf_attr1", IPV4)));

  AddRelationWithKeys (IMAGE, attrdeflist (
    attrdef ("image_attr1", IPV4),
    attrdef ("image_attr2", IPV4)));

  AddRelationWithKeys (PREDICTION, attrdeflist (
    attrdef ("prediction_attr1", IPV4),
    attrdef ("prediction_attr2", IPV4),
    attrdef ("prediction_attr3", IPV4)));

  AddRelationWithKeys (RESULT, attrdeflist (
    attrdef ("result_attr1", IPV4),
    attrdef ("result_attr2", IPV4),
    attrdef ("result_attr3", IPV4),
    attrdef ("result_attr4", IPV4)));

}

void
Mlprovenance::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsInsertEvent (tuple, CLF))
    {
      R1Eca0Ins (tuple);
    }
  if (IsRecvEvent (tuple, PCLF))
    {
      R1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PLIST))
    {
      R2_eca (tuple);
    }
  if (IsRecvEvent (tuple, PITERATE))
    {
      R3_eca (tuple);
    }
  if (IsRecvEvent (tuple, PITERATE))
    {
      R4_eca (tuple);
    }
  if (IsInsertEvent (tuple, ASSOCIATIONRULE))
    {
      R5Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, PREDICTION))
    {
      R5Eca1Ins (tuple);
    }
  if (IsRecvEvent (tuple, IDENTIFIEDPATTERN))
    {
      R6_eca (tuple);
    }
  if (IsRecvEvent (tuple, CLIST))
    {
      R7_eca (tuple);
    }
  if (IsRecvEvent (tuple, CITERATE))
    {
      R8_eca (tuple);
    }
  if (IsRecvEvent (tuple, CITERATE))
    {
      R9_eca (tuple);
    }
}

void
Mlprovenance::R1Eca0Ins (Ptr<Tuple> clf)
{
  RAPIDNET_LOG_INFO ("R1Eca0Ins triggered");

  Ptr<Tuple> result = clf;

  result->Assign (Assignor::New ("Enabled",
    FInitClassifier::New (
      VarExpr::New ("clf_attr2"))));

  result = result->Project (
    PCLF,
    strlist ("clf_attr1",
      "clf_attr2",
      "Enabled"),
    strlist ("pClf_attr1",
      "pClf_attr2",
      "pClf_attr3"));

  SendLocal (result);
}

void
Mlprovenance::R1_eca (Ptr<Tuple> pClf)
{
  RAPIDNET_LOG_INFO ("R1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (IMAGE)->Join (
    pClf,
    strlist ("image_attr1"),
    strlist ("pClf_attr1"));

  result->Assign (Assignor::New ("L",
    FClassifyImage::New (
      VarExpr::New ("image_attr3"),
      VarExpr::New ("pClf_attr2"))));

  result = result->Project (
    PLIST,
    strlist ("pClf_attr1",
      "image_attr2",
      "L"),
    strlist ("pList_attr1",
      "pList_attr2",
      "pList_attr3"));

  SendLocal (result);
}

void
Mlprovenance::R2_eca (Ptr<Tuple> pList)
{
  RAPIDNET_LOG_INFO ("R2_eca triggered");

  Ptr<Tuple> result = pList;

  result->Assign (Assignor::New ("N",
    ValueExpr::New (Int32Value::New (1))));

  result = result->Project (
    PITERATE,
    strlist ("pList_attr1",
      "pList_attr2",
      "N",
      "pList_attr3"),
    strlist ("pIterate_attr1",
      "pIterate_attr2",
      "pIterate_attr3",
      "pIterate_attr4"));

  SendLocal (result);
}

void
Mlprovenance::R3_eca (Ptr<Tuple> pIterate)
{
  RAPIDNET_LOG_INFO ("R3_eca triggered");

  Ptr<Tuple> result = pIterate;

  result->Assign (Assignor::New ("N",
    Operation::New (RN_PLUS,
      VarExpr::New ("pIterate_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_LT,
      VarExpr::New ("pIterate_attr3"),
      FSize::New (
        VarExpr::New ("pIterate_attr4")))));

  result = result->Project (
    PITERATE,
    strlist ("pIterate_attr1",
      "pIterate_attr2",
      "N",
      "pIterate_attr4"),
    strlist ("pIterate_attr1",
      "pIterate_attr2",
      "pIterate_attr3",
      "pIterate_attr4"));

  SendLocal (result);
}

void
Mlprovenance::R4_eca (Ptr<Tuple> pIterate)
{
  RAPIDNET_LOG_INFO ("R4_eca triggered");

  Ptr<Tuple> result = pIterate;

  result->Assign (Assignor::New ("AnotherList",
    FItem::New (
      VarExpr::New ("pIterate_attr4"),
      VarExpr::New ("pIterate_attr3"))));

  result->Assign (Assignor::New ("Item",
    FItem::New (
      VarExpr::New ("AnotherList"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("Prob",
    FItem::New (
      VarExpr::New ("AnotherList"),
      ValueExpr::New (Int32Value::New (2)))));

  result = result->Select (Selector::New (
    Operation::New (RN_LTE,
      VarExpr::New ("pIterate_attr3"),
      FSize::New (
        VarExpr::New ("pIterate_attr4")))));

  result = result->Project (
    PREDICTION,
    strlist ("pIterate_attr1",
      "pIterate_attr2",
      "Item",
      "Prob"),
    strlist ("prediction_attr1",
      "prediction_attr2",
      "prediction_attr3",
      "prediction_attr4"));

  Insert (result);
}

void
Mlprovenance::R5Eca0Ins (Ptr<Tuple> associationrule)
{
  RAPIDNET_LOG_INFO ("R5Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PREDICTION)->Join (
    associationrule,
    strlist ("prediction_attr3", "prediction_attr1"),
    strlist ("associationrule_attr2", "associationrule_attr1"));

  result->Assign (Assignor::New ("Prob",
    Operation::New (RN_TIMES,
      VarExpr::New ("associationrule_attr4"),
      VarExpr::New ("prediction_attr4"))));

  result = result->Project (
    IDENTIFIEDPATTERN,
    strlist ("associationrule_attr1",
      "prediction_attr2",
      "associationrule_attr2",
      "associationrule_attr3",
      "Prob"),
    strlist ("identifiedPattern_attr1",
      "identifiedPattern_attr2",
      "identifiedPattern_attr3",
      "identifiedPattern_attr4",
      "identifiedPattern_attr5"));

  SendLocal (result);
}

void
Mlprovenance::R5Eca1Ins (Ptr<Tuple> prediction)
{
  RAPIDNET_LOG_INFO ("R5Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (ASSOCIATIONRULE)->Join (
    prediction,
    strlist ("associationrule_attr2", "associationrule_attr1"),
    strlist ("prediction_attr3", "prediction_attr1"));

  result->Assign (Assignor::New ("Prob",
    Operation::New (RN_TIMES,
      VarExpr::New ("associationrule_attr4"),
      VarExpr::New ("prediction_attr4"))));

  result = result->Project (
    IDENTIFIEDPATTERN,
    strlist ("prediction_attr1",
      "prediction_attr2",
      "prediction_attr3",
      "associationrule_attr3",
      "Prob"),
    strlist ("identifiedPattern_attr1",
      "identifiedPattern_attr2",
      "identifiedPattern_attr3",
      "identifiedPattern_attr4",
      "identifiedPattern_attr5"));

  SendLocal (result);
}

void
Mlprovenance::R6_eca (Ptr<Tuple> identifiedPattern)
{
  RAPIDNET_LOG_INFO ("R6_eca triggered");

  Ptr<Tuple> result = identifiedPattern;

  result->Assign (Assignor::New ("L",
    FClassify::New (
      VarExpr::New ("identifiedPattern_attr4"))));

  result = result->Project (
    CLIST,
    strlist ("identifiedPattern_attr1",
      "identifiedPattern_attr2",
      "L",
      "identifiedPattern_attr4",
      "identifiedPattern_attr5"),
    strlist ("cList_attr1",
      "cList_attr2",
      "cList_attr3",
      "cList_attr4",
      "cList_attr5"));

  SendLocal (result);
}

void
Mlprovenance::R7_eca (Ptr<Tuple> cList)
{
  RAPIDNET_LOG_INFO ("R7_eca triggered");

  Ptr<Tuple> result = cList;

  result->Assign (Assignor::New ("N",
    ValueExpr::New (Int32Value::New (1))));

  result = result->Project (
    CITERATE,
    strlist ("cList_attr1",
      "cList_attr2",
      "N",
      "cList_attr3",
      "cList_attr4",
      "cList_attr5"),
    strlist ("cIterate_attr1",
      "cIterate_attr2",
      "cIterate_attr3",
      "cIterate_attr4",
      "cIterate_attr5",
      "cIterate_attr6"));

  SendLocal (result);
}

void
Mlprovenance::R8_eca (Ptr<Tuple> cIterate)
{
  RAPIDNET_LOG_INFO ("R8_eca triggered");

  Ptr<Tuple> result = cIterate;

  result->Assign (Assignor::New ("N",
    Operation::New (RN_PLUS,
      VarExpr::New ("cIterate_attr3"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_LT,
      VarExpr::New ("cIterate_attr3"),
      FSize::New (
        VarExpr::New ("cIterate_attr4")))));

  result = result->Project (
    CITERATE,
    strlist ("cIterate_attr1",
      "cIterate_attr2",
      "N",
      "cIterate_attr4",
      "cIterate_attr5",
      "cIterate_attr6"),
    strlist ("cIterate_attr1",
      "cIterate_attr2",
      "cIterate_attr3",
      "cIterate_attr4",
      "cIterate_attr5",
      "cIterate_attr6"));

  SendLocal (result);
}

void
Mlprovenance::R9_eca (Ptr<Tuple> cIterate)
{
  RAPIDNET_LOG_INFO ("R9_eca triggered");

  Ptr<Tuple> result = cIterate;

  result->Assign (Assignor::New ("AnotherList",
    FItem::New (
      VarExpr::New ("cIterate_attr4"),
      VarExpr::New ("cIterate_attr3"))));

  result->Assign (Assignor::New ("Person",
    FItem::New (
      VarExpr::New ("AnotherList"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("Prob2",
    FItem::New (
      VarExpr::New ("AnotherList"),
      ValueExpr::New (Int32Value::New (2)))));

  result->Assign (Assignor::New ("Prob",
    VarExpr::New ("cIterate_attr6")));

  result = result->Select (Selector::New (
    Operation::New (RN_LTE,
      VarExpr::New ("cIterate_attr3"),
      FSize::New (
        VarExpr::New ("cIterate_attr4")))));

  result = result->Project (
    RESULT,
    strlist ("cIterate_attr1",
      "cIterate_attr2",
      "cIterate_attr5",
      "Person",
      "Prob"),
    strlist ("result_attr1",
      "result_attr2",
      "result_attr3",
      "result_attr4",
      "result_attr5"));

  Insert (result);
}

